- gene/etl/merge.py
- gene/query.py
- gene/version.py
- tests/unit/data/etl_data/hgnc_20210810.json
- tests/unit/data/etl_data/ncbi_info_20210813.tsv
- tests/unit/test_query.py
close #126 
This also adds `location_annotations` to extensions if the field exists
> feat: return all source locations in normalize response (#126)

- .github/workflows/github-actions.yml
- README.md
- gene/database.py
- gene/version.py
- tests/unit/test_database_and_etl.py
Added an extra safety check in the test_database_and_etl. Theoretically it should never happen since an exception would be raised in the db init, but added just in case the env var changes and it is not updated in the tests.
> feat: ensure test and aws env vars are not set at same time (staging)

- Pipfile
- gene/version.py
- requirements-dev.txt
- requirements.txt
- setup.cfg
This tracks the VRS 1.2.X branch. There were some mismatches with the ~=0.8.X dev versions.
> build: update ga4gh.vrs version to ~= 0.7.8

- Pipfile
- gene/version.py
- requirements-dev.txt
- requirements.txt
- setup.cfg
Close #131 
Notes:
- ga4gh.vrsatile.pydantic ~= 0.0.12
- ga4gh.vrs ~= 0.8.1
> build: update ga4gh packages to use VRS 1.3 models

- docs/source/managing_data/loading_and_updating_data.rst
- gene/cli.py
- gene/database/database.py
- gene/database/dynamodb.py
- gene/database/postgresql.py
- gene/database/postgresql/add_indexes.sql
- gene/database/postgresql/create_record_lookup_view.sql
- gene/database/postgresql/create_tables.sql
- setup.cfg
Adds a console entrypoint `gene_norm_check_db` that exits with status code 1 if the DB isn't set up or if a few basic queries fail.
Useful for the way I'm trying to get Docker to work.
> feat: add DB status check entrypoint

- CITATION.cff
- gene/database/database.py
- gene/version.py
close #188 
per slack, these checks are already performed on dynamodb initialization and not necessary in the DB helper
> fix: prevent redundant/incorrect AWS confirmation checks

- gene/etl/merge.py
> fix: remove duplicate xrefs from merged records

- gene/query.py
- tests/unit/test_emit_warnings.py
I don't know if this is, like, essential work, but I was thinking about it the other day and wanted to see how code blocks in docstrings looked in the sphinx-generated pages, so... here it is.
Also made some of the query methods actually private to make the API page cleaner. I am pretty sure most of this stuff is not intended to be used by external methods, like, ever but we could always refactor or make some of it more usable by other objects.
> docs: touch up query API documentation

- gene/database/postgresql.py
- gene/database/postgresql/add_indexes.sql
- gene/database/postgresql/create_tables.sql
- gene/database/postgresql/delete_normalized_concepts.sql
- gene/database/postgresql/drop_indexes.sql
I might be reaching here, but normalized delete times were sorta slow in postgres because they were iteratively deleting every record in the merged concepts table. This PR adds some repeated SQL code in a few places but basically tears down and reconstructs all of the merged concepts dependencies so you can simply drop the table rather than clearing it row by row. It should be safe since it still happens in one transaction but definitely makes for less elegant code. On the bright side, it's like 10 times faster now.
I also went through and made all the query strings class variables so they're only defined once, rather than being recreated on every method call. This is a teeny tiny optimization but is more in line with how Python apps tend to do this.
> perf: improve PG normalized concept deletion

- .readthedocs.yaml
- setup.cfg
Progress on #185. A lot of the automation needs to happen on the rtd side, which is a little unfortunate, but this enables the basics.
see eg https://gene-normalizer.readthedocs.io/en/latest/
> docs: provide readthedocs integration

- .github/workflows/github-actions.yml
- setup.cfg
the sphinx test GitHub Action uses a Docker image that has an old version of pip on it, resulting in poor dependency conflict management with respect to Pydantic v1 vs v2. This pr forces it to upgrade to the latest version to ensure that it handles it better.
> ci: use latest pip in sphinx test

- docs/source/normalizing_data/normalization.rst
- gene/etl/merge.py
- gene/query.py
- gene/version.py
- tests/unit/test_query.py
We've already been storing a strand value in the DB for merged records, but we weren't providing it in normalized search results. Pretty simple PR here to add it as an Extension.
This unearthed a separate, interesting issue regarding about 300 cases of conflicting strand values within normalized groups. Going to make a separate issue.
> feat: provide strand in normalized record

- gene/cli.py
- setup.cfg
Resolve #248 
We could compartmentalize this a bit by splitting the ETL-specific functions into a `gene.etl.cli` module and moving everything else to a `gene.database.cli` module, but I think we still need to put the `try import/except` block into the middle of the file CLI rather than the top to avoid other weird side effects.
> fix: catch ETL module import errors

- gene/etl/ncbi.py
> fix: correct gene info file glob typo

- gene/etl/hgnc.py
- tests/unit/test_hgnc_source.py
> feat: update HGNC license

- .github/workflows/release.yml
Addresses #282 for main branch
Notes:
- Followed https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
- Did not include [Signing the distribution packages](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#signing-the-distribution-packages)
- In `publish-to-pypi`, removed `if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes` since we only make a release when a GH release is created.
> cicd: update release.yaml (publish python distribution to pypi)

- src/gene/main.py
> refactor: remove unused error handling

- docs/source/normalizing_data/vrs_compliance.rst
close #286 
Notes:
* branch updates:
* `main` --> `vrs-1.x` (VRS 1.x) . Locked branch (rule applies to any branches that match `vrs-*`). Maybe I should just rename to `vrs-1.3`? 
* `staging` --> `main` (VRS 2.x)
* We will only work off of `main` branch and no longer need a `staging` branch
* For VRS 1.x, just kept as main branch. Wasn't sure if we wanted to point to 1.3 branch or not. 
@jsstevenson does this work for you? If so, I will go ahead and make these changes for disease and therapy.
> docs: update VRS compliance

- Pipfile
- pyproject.toml
Not updating ga4gh.vrs:
https://peps.python.org/pep-0440/#compatible-release
> If a pre-release, post-release or developmental release is named in a compatible release clause as V.N.suffix, then the suffix is ignored when determining the required prefix match:
> 
> ```
> ~= 1.4.5a4
> >= 1.4.5a4, == 1.4.*
> ```
> build: properly pin pydantic v2 major version

- src/gene/main.py
- src/gene/query.py
- tests/unit/test_endpoints.py
- tests/unit/test_ensembl_source.py
- tests/unit/test_hgnc_source.py
- tests/unit/test_ncbi_source.py
- tests/unit/test_query.py
* `QueryHandler.search()` takes a single `sources` param, which is a list of `SourceName` instances, rather than `incl` and `excl` strings. IMO it's easier to work from enums when you're accessing programmatically.
* Move source name parsing logic out to the API endpoint method. Makes more sense to do it there IMO, since that's the only place that you'd be getting a big mashed up string rather than specifically defined source names.
* Remove the `excl` parameter. It doesn't strike me as being particularly useful; I think it was put there for "why not?" reasons.
> feat!: use enumerated source name types in search/

- src/gene/cli.py
- src/gene/database/dynamodb.py
- src/gene/database/postgresql.py
- src/gene/etl/base.py
- src/gene/etl/ensembl.py
- src/gene/etl/hgnc.py
- src/gene/etl/merge.py
- src/gene/etl/ncbi.py
- src/gene/etl/update.py
I also made an issue (https://github.com/GenomicMedLab/gene-normalizer-api/issues/16) -- down the road we could get pretty aggressive with debug logging and turn it off on the API itself
> chore: overhaul logging

- README.md
add parse-able description section from readme for richer/more verbose summary than what's given in pyproject.toml
> docs: add description metadata

- README.md
- docs/scripts/generate_normalize_figure.py
- docs/source/_static/html/normalize_example.html
- docs/source/index.rst
- docs/source/managing_data/index.rst
- docs/source/normalizing_data/sources.rst
- src/gene/database/dynamodb.py
- src/gene/database/postgresql.py
- src/gene/database/postgresql/add_fkeys.sql
- src/gene/database/postgresql/add_indexes.sql
- src/gene/database/postgresql/create_record_lookup_view.sql
- src/gene/database/postgresql/create_tables.sql
- src/gene/database/postgresql/delete_normalized_concepts.sql
- src/gene/database/postgresql/drop_fkeys.sql
- src/gene/database/postgresql/drop_indexes.sql
- src/gene/etl/ensembl.py
- src/gene/etl/hgnc.py
- src/gene/etl/merge.py
- src/gene/etl/ncbi.py
- src/gene/query.py
- src/gene/schemas.py
- tests/conftest.py
- tests/unit/test_database_and_etl.py
- tests/unit/test_ensembl_source.py
- tests/unit/test_hgnc_source.py
- tests/unit/test_ncbi_source.py
- tests/unit/test_query.py
- tests/unit/test_schemas.py
The original source Gene object structure was sort of just something we (Alex) came up with back in the day. Now we have a GKS object that doesn't distinguish between `xrefs` and `associated_with` (this was always kind of a funny distinction anyway). This PR builds toward usage of the GKS Gene object across all response types by merging `associated_with` into `xrefs`.
Most of this PR is just ctrl+f find/replace, but there is some small refactoring of the ETL methods since this change enables some simplification.
> feat!: collapse `associated_with` into `xrefs`

- src/gene/database/postgresql.py
Fixes two issues with the Postgres database class:
1. The error message when calling psql from `load_from_remote` wasn't very helpful, printing the return code rather than the system_call string.
2. `psql -W password` doesn't work that way, so I've changed it to always use the connection url when calling out to psql and pg_dump.
> fix: handle password param in postgres connection

- .github/workflows/checks.yaml
I started noticing some problems with the Sphinx test action over [here](https://github.com/GenomicMedLab/cool-seq-tool/pull/222) but hadn't echoed those changes back to this repo. This should provide basic testing of doc building on the GitHub CICD side.
> cicd: use working docs test

- .github/workflows/checks.yaml
- docs/source/api/api/gene.etl.exceptions.rst
- docs/source/api/api/gene.etl.update.rst
- docs/source/api/index.rst
- docs/source/managing_data/dynamodb.rst
- docs/source/managing_data/loading_and_updating_data.rst
- docs/source/managing_data/postgresql.rst
- docs/source/usage.rst
- src/gene/query.py
- src/gene/schemas.py
* pass proper dependencies to docs test action
* fix some dead links in docs
* fix a ruff cleanup typo
> cicd: do cleanup to make checks happy

- src/gene/cli.py
- src/gene/etl/base.py
- src/gene/etl/ncbi.py
- src/gene/etl/update.py
* also misc logging improvements in data update methods
> feat: configure logging in CLI

- src/gene/cli.py
- src/gene/database/dynamodb.py
- src/gene/database/postgresql.py
- src/gene/etl/base.py
- src/gene/etl/ensembl.py
- src/gene/etl/hgnc.py
- src/gene/etl/merge.py
- src/gene/etl/ncbi.py
Pull in relevant changes from #311 and #342 
* Should fail multiple CI checks -- in particular, Ruff fixes were made on the [big update branch](https://github.com/cancervariants/gene-normalization/tree/interface-updates-epic), not here
> fix: correctly configure logging

- src/gene/__init__.py
- src/gene/query.py
pulling over changes from another commit on the API breaking branch
> fix: more logging config fixes

- pyproject.toml
- src/gene/query.py
- src/gene/schemas.py
- tests/unit/test_query.py
- tests/unit/test_schemas.py
close #377 
* Update modules to vrs [2.0.0-ballot.2024-11.3](https://github.com/ga4gh/vrs/tree/2.0.0-ballot.2024-11.3) tag
* GKS `Gene` is now a `MappableConcept`
* `alternativeLabels` moved to `extensions` with `name='aliases'`
> feat!: update models to vrs 2.0.0 community review ballot

- README.md
- docs/source/index.rst
- docs/source/install.rst
- docs/source/normalizing_data/normalization.rst
- src/gene/query.py
- src/gene/schemas.py
- tests/unit/test_endpoints.py
- tests/unit/test_query.py
close #380
* also updates mappigns to include exactMatch relation for merged concept identifier
Comment:
In the future, we may want to consider also updating our `ConceptMappings` to leverage uri/urls since they are preferred
> feat!: remove `normalized_id` and leverage `MappableConcept.primaryCode`

- src/gene/query.py
> refactor: remove unnecessary `.lower()` call when creating concept mapping

- src/gene/query.py
- src/gene/schemas.py
- tests/unit/test_query.py
close #383
* Use `concept_id` as the CURIE
> fix!: `ConceptMapping.coding.code` should be a CURIE

- .github/workflows/checks.yaml
- docs/source/normalizing_data/normalization.rst
- src/gene/query.py
- src/gene/schemas.py
- tests/unit/test_query.py
- tests/unit/test_schemas.py
close #394
* correct `Coding` representation
* `system` MUST use `iriReference`, not a free-text label
* `code` MUST use syntax defined by the `system`
* `id` will use record `concept_id`
* `NAMESPACE_TO_SYSTEM_URI` is now a `MappingProxyType`
* Removes `SYSTEM_URI_TO_NAMESPACE` mapping (since it's no longer needed)
* Removes `NamespacePrefix.KZNF` since it doesn't seem to be used 
* temporarily update ci `test` job to use previous ubuntu version 
* New image was released 2 days ago, which is causing action to fail. I can make an issue in https://github.com/actions/runner-images later
> fix!: use correct representation of `Coding` object in `mappings`

- .github/workflows/checks.yaml
- .pre-commit-config.yaml
- pyproject.toml
catch up to https://github.com/GenomicMedLab/software-templates/releases/tag/2025.01.08
> cicd: update precommit + hooks

- README.md
- docs/source/index.rst
- docs/source/install.rst
- docs/source/normalizing_data/normalization.rst
- pyproject.toml
- src/gene/query.py
- src/gene/schemas.py
- tests/unit/test_endpoints.py
- tests/unit/test_query.py
closes #404 
@korikuzma @jsstevenson Notes:
- This PR replaces the `primaryCode` attribute with `primaryCoding`
- I had trouble getting the `code` attribute to all uppercase as shown in the issue [example](https://github.com/cancervariants/gene-normalization/issues/404). Should this attribute be uppercase?
- I left the `UnmergedNormalizationService` class the same. Do we want to update this?
> feat!: Update to include primaryCoding attribute
