gene/etl/ensembl.py, gene/etl/hgnc.py
=> Add download exception

dynamodb_revisions/add_other_id_refs.py
=> Add other_id references

.github/workflows/github-actions.yml, Pipfile, requirements-dev.txt, requirements.txt
Fixes EB instance failing due to package version conflicts.
=> Update Package Requirements

gene/etl/ensembl.py, gene/etl/hgnc.py, gene/etl/ncbi.py
Currently looking this up for myself: https://www.readinglesson.com/
=> Correcting refactor errors

dynamodb_revisions/add_xref_refs.py, gene/__init__.py, gene/etl/ensembl.py, gene/etl/hgnc.py, gene/etl/ncbi.py, gene/query.py, gene/schemas.py, tests/unit/data/genes.json, tests/unit/test_ensembl_source.py, tests/unit/test_hgnc_source.py, tests/unit/test_ncbi_source.py
=> Xref stuff

Pipfile, gene/__init__.py, gene/query.py, gene/schemas.py, gene/version.py, gene/vrs_locations/chromosome_location.py, gene/vrs_locations/sequence_location.py, requirements-dev.txt, requirements.txt, setup.cfg, tests/unit/test_ensembl_source.py, tests/unit/test_hgnc_source.py, tests/unit/test_ncbi_source.py, tests/unit/test_query.py
=> Issue 105: Set use_enum_values, response_datetime is a str, update packages

.ebextensions/01app.config, Pipfile, gene/version.py, requirements-dev.txt, requirements.txt
closes #104 : Installs via eb commands
=> Issue 104: Remove EB dependencies from pipfile

gene/__init__.py
=> Issue 110: Allow SEQREPO_DATA_PATH to be set by env var

.flake8, gene/cli.py, gene/etl/base.py, gene/etl/ensembl.py, gene/etl/ncbi.py, tests/unit/data/etl_data/ensembl_105.gff3, tests/unit/test_database_and_etl.py, tests/unit/test_ensembl_source.py
=> Issue 82: Download latest NCBI and Ensembl data

.github/workflows/github-actions.yml, .github/workflows/release.yml, CITATION.cff, README.md, gene/database.py, gene/version.py, tests/unit/test_database_and_etl.py
Close #158 
Tried using git rebase! It picked up some older commits from staging
=> feat: ensure test and aws env vars are not set at same time (main)

Pipfile, gene/version.py, requirements-dev.txt, requirements.txt, setup.cfg
=> build: do not pin exact version for ga4gh.vrsatile.pydantic

Pipfile, requirements-dev.txt, requirements.txt, setup.cfg
Updates ga4gh.vrs + ga4gh.vrsatile.pydantic versions
=> build: update ga4gh versions (staging)

README.md, gene/__init__.py, gene/etl/base.py, gene/version.py
=> refactor: rename SEQREPO_DATA_PATH --> SEQREPO_ROOT_DIR (staging)

docs/source/managing_data/loading_and_updating_data.rst, gene/cli.py, gene/database/database.py, gene/database/dynamodb.py, gene/database/postgresql.py, gene/database/postgresql/add_indexes.sql, gene/database/postgresql/create_record_lookup_view.sql, gene/database/postgresql/create_tables.sql, setup.cfg
=> feat: add DB status check entrypoint

CITATION.cff, gene/database/database.py, gene/version.py
=> fix: prevent redundant/incorrect AWS confirmation checks

gene/database/postgresql.py, gene/database/postgresql/add_indexes.sql, gene/database/postgresql/create_tables.sql, gene/database/postgresql/delete_normalized_concepts.sql, gene/database/postgresql/drop_indexes.sql
=> perf: improve PG normalized concept deletion

README.md, docs/source/managing_data/loading_and_updating_data.rst, gene/cli.py
=> fix!: use more precise name for CLI source option

.readthedocs.yaml, setup.cfg
=> docs: provide readthedocs integration

README.md, docs/source/api/database_api.rst, docs/source/usage.rst, gene/database/database.py, gene/database/postgresql.py, gene/query.py
Added some more information regarding database construction in response to a question on the GA4GH slack.
=> docs: add more usage details

docs/source/managing_data/dynamodb.rst, gene/database/dynamodb.py, tests/unit/test_database_and_etl.py
=> feat: optionally define dynamo table names via environment variable

docs/source/conf.py
=> fix: preserve arg defaults in docs

docs/source/conf.py
=> doc: preserve arg defaults in docs

setup.cfg
I'm not 100% sure that this is going to work for all of them, but I'm trying to fill these links in
=> chore: add PyPI metadata

setup.cfg
=> chore: add PyPI metadata (metaschema)

docs/source/normalizing_data/normalization.rst, gene/etl/merge.py, gene/query.py, tests/unit/test_query.py
=> feat: provide strand in normalized record (metaschema)

gene/database/database.py, gene/database/dynamodb.py, gene/database/postgresql.py, gene/etl/merge.py, gene/query.py, gene/schemas.py, tests/unit/test_database_and_etl.py
Got tired of rewriting the DynamoDB scan() pattern every time we want to grab all of the data.
=> feat: add get_all_records DB method 

gene/database/database.py, gene/database/dynamodb.py, gene/database/postgresql.py, gene/etl/merge.py, gene/query.py, gene/schemas.py, tests/unit/test_database_and_etl.py
=> feat: add get_all_records DB method

gene/etl/hgnc.py
high priority to make GH actions pass (annoying)
=> refactor: use isinstance instead of type() check

docs/source/managing_data/dynamodb.rst, gene/database/dynamodb.py, gene/etl/hgnc.py, gene/version.py, tests/unit/test_database_and_etl.py
close #215 
this will break dynamodb/etc so maybe we hold off from merging, or merge to a prerelease version? (I haven't bumped version yet in this PR for this reason)
=> feat!: store source metadata in concepts table

gene/main.py, gene/query.py, gene/schemas.py, tests/unit/test_ensembl_source.py, tests/unit/test_hgnc_source.py, tests/unit/test_ncbi_source.py, tests/unit/test_query.py
=> feat!: remove search result formatting options 

docs/source/managing_data/dynamodb.rst, gene/database/dynamodb.py, gene/etl/hgnc.py, gene/version.py, tests/unit/test_database_and_etl.py
=> feat!: merge concepts and source dynamodb tables

gene/etl/hgnc.py, tests/unit/test_hgnc_source.py
=> feat: update HGNC license

gene/main.py
=> fix: set response_model_exclude_none=True in /normalize

.github/workflows/close_issue.yml
=> cicd: add gh action for closing issue on staging branch

Pipfile, setup.cfg, tests/unit/test_endpoints.py
=> test: add basic route tests 

pyproject.toml
Conveniently, since I did the branches wrong the first time, I don't need to make a new PR for the old branch
=> build: define build system

.pre-commit-config.yaml, pyproject.toml
Note that we are taking on a LOT of linting/formatting failures here -- these have been fixed in a separate branch, but I want to get these pins onto main for now.
=> style: pin ruff version from template

README.md
=> docs: fix api reference link in readme

tests/conftest.py, tests/unit/test_ensembl_source.py, tests/unit/test_ncbi_source.py, tests/unit/test_query.py
Acutely felt #330 while doing this
=> test: update fixtures

docs/source/normalizing_data/normalization.rst, docs/source/normalizing_data/sources.rst, pyproject.toml, src/gene/query.py, src/gene/schemas.py, src/gene/version.py, tests/conftest.py, tests/unit/test_ensembl_source.py, tests/unit/test_ncbi_source.py, tests/unit/test_query.py, tests/unit/test_schemas.py
close #330 
@jsstevenson let me know if you'd rather these be two separate PRs
=> build!: update ga4gh.vrs version + reduce vrs id checks in tests

.github/workflows/checks.yaml, .github/workflows/pr-priority-label.yaml, .pre-commit-config.yaml, LICENSE, Pipfile, README.md, docs/scripts/generate_normalize_figure.py, docs/source/conf.py, pyproject.toml, src/gene/__init__.py, src/gene/cli.py, src/gene/database/database.py, src/gene/database/dynamodb.py, src/gene/database/postgresql.py, src/gene/etl/base.py, src/gene/etl/ensembl.py, src/gene/etl/hgnc.py, src/gene/etl/merge.py, src/gene/etl/ncbi.py, src/gene/main.py, src/gene/query.py, src/gene/schemas.py, tests/unit/test_database_and_etl.py, tests/unit/test_emit_warnings.py, tests/unit/test_ensembl_source.py, tests/unit/test_hgnc_source.py, tests/unit/test_ncbi_source.py, tests/unit/test_query.py
=> style: update ruff to 0.5.0

pyproject.toml
* removes black + extra comment
=> chore: remove unused configs in pyproject.toml

src/gene/__init__.py, src/gene/etl/base.py, src/gene/etl/hgnc.py, src/gene/etl/ncbi.py, src/gene/query.py, src/gene/schemas.py, tests/unit/test_hgnc_source.py, tests/unit/test_ncbi_source.py, tests/unit/test_query.py, tests/unit/test_schemas.py
close #339, #247
* remove commented out VRS Chromosome Location code
* rename + update HGNC/NCBI ETL private methods that referenced VRS CL
=> refactor: remove unused code

src/gene/schemas.py
* replace constr with Annotated and StringConstraints
=> refactor: resolve Pylance warnings

.github/workflows/checks.yaml, pyproject.toml, src/gene/database/postgresql.py, src/gene/query.py, src/gene/schemas.py, tests/unit/test_hgnc_source.py, tests/unit/test_ncbi_source.py
* https://github.com/GenomicMedLab/software-templates/pull/66
=> build!: require python >=3.11

docs/source/normalizing_data/normalization.rst, src/gene/query.py, src/gene/schemas.py, tests/unit/test_query.py
Per discussion here: https://github.com/ga4gh/gks-core/pull/107
=> fix!: `system` should use source homepage

.github/workflows/checks.yaml, docs/source/contributing.rst, docs/source/install.rst, pyproject.toml
=> chore!: rename optional dependency

src/gene/query.py, src/gene/schemas.py, tests/unit/test_query.py
=> fix!: `xrefs` should have `exactMatch` for `ConceptMapping.relation`

docs/source/conf.py, docs/source/managing_data/loading_and_updating_data.rst, docs/source/reference/api/etl/gene.etl.update.rst, docs/source/reference/index.rst, pyproject.toml, src/gene/cli.py, src/gene/config.py, src/gene/etl/update.py, src/gene/logs.py, src/gene/schemas.py
* Use a single command with subcommands to better conform to POSIX/GNU norms
* Move internal update routines to a dedicated ETL module. Also add basic config and logging modules for better/more consistent encapsulation
* Update docs
* matches lab template/implementation for the Disease Normalizer.
=> feat!: overhaul CLI

docs/source/install.rst, docs/source/managing_data/postgresql.rst
=> docs: update documentation for CLI changes in #405
